name: Steps Modifier

on:
  schedule:
    # 每天 05:30 UTC = 北京时间 13:30
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Random delay (up to 60 秒之前)
      run: |
        DELAY=$((RANDOM % 60))
        echo "Sleeping for $DELAY seconds..."
        sleep $DELAY

    - name: Run step modifier script
      env:
        TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        ACCOUNTS_AND_PASSWORDS: ${{ secrets.ACCOUNTS_AND_PASSWORDS }}
      run: |
        python steps.py
